=== cjpl/rome/rome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Described some enumerated types</xs:documentation>
	</xs:annotation>
	<xs:simpleType name="RootType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Float_t"/>
			<xs:enumeration value="ULong_t"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IncludeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="global"/>
			<xs:enumeration value="local"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HistTypeDesc">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TH1C"/>
			<xs:enumeration value="TH1D"/>
			<xs:enumeration value="TH1F"/>
			<xs:enumeration value="TH1I"/>
			<xs:enumeration value="TH1S"/>
			<xs:enumeration value="TH2C"/>
			<xs:enumeration value="TH2D"/>
			<xs:enumeration value="TH2F"/>
			<xs:enumeration value="TH2I"/>
			<xs:enumeration value="TH2S"/>
			<xs:enumeration value="TH3C"/>
			<xs:enumeration value="TH3D"/>
			<xs:enumeration value="TH3F"/>
			<xs:enumeration value="TH3I"/>
			<xs:enumeration value="TH3S"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MidasType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DWORD"/>
			<xs:enumeration value="float"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation>
		<xs:documentation>Describe general types</xs:documentation>
	</xs:annotation>
	<xs:complexType name="AuthorDesc">
		<xs:sequence>
			<xs:element name="AuthorName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorInstitute" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorCollaboration" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorEmail" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ExperimentDesc">
		<xs:sequence>
			<xs:element name="ExperimentName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ExperimentShortCut" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ProgramName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FrameworkDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IncludeDesc">
		<xs:sequence>
			<xs:element name="IncludeName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="IncludeType" type="IncludeType" default="global" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterFieldDesc">
		<xs:sequence>
			<xs:element name="SPFieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SPFieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SPFieldInitialization" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SPFieldComment" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterGroupDesc">
		<xs:sequence>
			<xs:element name="SPGroupName" type="xs:string"/>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe types used by subfolders</xs:documentation>
	</xs:annotation>
	<xs:complexType name="FieldDesc">
		<xs:sequence>
			<xs:element name="FieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FieldComment" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FieldInitialization" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ArraySize" type="xs:string" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataBasePath" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FolderDesc">
		<xs:sequence>
			<xs:element name="FolderName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FolderTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ArraySize" type="xs:string" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataBaseAccess" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ChangeableClassFile" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FolderVersion" type="xs:integer" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FolderDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Include" type="IncludeDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Field" type="FieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Folder" type="FolderDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe tasks</xs:documentation>
	</xs:annotation>
	<xs:complexType name="HistogramDesc">
		<xs:sequence>
			<xs:element name="HistName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="HistTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistFolderName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistFolderTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistType" type="HistTypeDesc" minOccurs="1" maxOccurs="1"/>
			<xs:element name="HistArraySize" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParametersDesc">
		<xs:sequence>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TaskDesc">
		<xs:sequence>
			<xs:element name="TaskName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TaskEventId" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TaskVersion" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TaskDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Include" type="IncludeDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Histogram" type="HistogramDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameters" type="SteeringParametersDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe trees</xs:documentation>
	</xs:annotation>
	<xs:complexType name="BranchDesc">
		<xs:sequence>
			<xs:element name="BranchName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="RelatedFolder" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TreeDesc">
		<xs:sequence>
			<xs:element name="TreeName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TreeTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Branch" type="BranchDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe elements used by MidasBanks</xs:documentation>
	</xs:annotation>
	<xs:complexType name="EventHeaderDesc">
		<xs:sequence>
			<xs:element name="Folder" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="EventId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TriggerMask" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SerialNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TimeStamp" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BankDesc">
		<xs:sequence>
			<xs:element name="BankName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankType" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BankFieldDesc">
		<xs:sequence>
			<xs:element name="BankFieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankFieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankFieldSize" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StructuredBankDesc">
		<xs:sequence>
			<xs:element name="BankName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankField" type="BankFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe overall document</xs:documentation>
	</xs:annotation>
	<xs:element name="ROMEFrameworkDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Experiment" type="ExperimentDesc" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Folders" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Folder" type="FolderDesc" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Tasks" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Task" type="TaskDesc" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Trees" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Tree" type="TreeDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="GlobalSteeringParameters" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MidasBanks" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="EventHeader" type="EventHeaderDesc" minOccurs="0" maxOccurs="1"/>
							<xs:element name="Bank" type="BankDesc" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="StructuredBank" type="StructuredBankDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cjpl/rome/rome/examples/tree_write_read/tree_write_read.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>TWR</ExperimentShortCut>
		<ProgramName>Sample</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Data</FolderName>
			<Field>
				<FieldName>Value</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Value of Folder Data</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillTree</TaskName>
		</Task>
		<Task>
			<TaskName>PrintValue</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<Branch>
				<BranchName>DataBranch</BranchName>
				<RelatedFolder>Data</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/examples/tree_write_read/tree_write_read.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>TWR</ExperimentShortCut>
		<ProgramName>Sample</ProgramName>
		<ProgramDefinitionVersion>$Rev$</ProgramDefinitionVersion>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Data1</FolderName>
			<Field>
				<FieldName>Value1</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Value of Folder Data</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>Data2</FolderName>
			<Field>
				<FieldName>Value2</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Value of Folder Data</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillTree</TaskName>
		</Task>
		<Task>
			<TaskName>PrintValue</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree1</TreeName>
			<Branch>
				<BranchName>DataBranch</BranchName>
				<RelatedFolder>Data1</RelatedFolder>
			</Branch>
		</Tree>
		<Tree>
			<TreeName>DataTree2</TreeName>
			<Branch>
				<BranchName>DataBranch</BranchName>
				<RelatedFolder>Data2</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/macros/macros.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>MCR</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>PMTData</FolderName>
			<ArraySize>10</ArraySize>
			<Field>
				<FieldName>ADC</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>ADC Value of a PMT</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>Sum</FolderName>
			<Field>
				<FieldName>ADCSum</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Sum of ADC Value of a PMT</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>TakingSum</TaskName>
		</Task>
	</Tasks>
	<UserDAQSystems>
		<UserDAQSystem>
			<DAQSystemName>dummy</DAQSystemName>
		</UserDAQSystem>
	</UserDAQSystems>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<Branch>
				<BranchName>pmt</BranchName>
				<RelatedFolder>PMTData</RelatedFolder>
			</Branch>
			<Branch>
				<BranchName>sum</BranchName>
				<RelatedFolder>Sum</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/tree_write_read2/tree_write_read2.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>TWR2</ExperimentShortCut>
		<ProgramName>Sample</ProgramName>
		<ProgramDefinitionVersion>$Rev$</ProgramDefinitionVersion>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Track</FolderName>
			<Field>
				<FieldName>ntrack</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment># of tracks</FieldComment>
				<FieldInitialization>0</FieldInitialization>
			</Field>
			<Field>
				<FieldName>particleid</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>[ntrack] geant particle code</FieldComment>
				<ArraySize>variable</ArraySize>
			</Field>
		</Folder>
		<Folder>
			<FolderName>RawPointerSplit</FolderName>
			<FolderTitle>Raw with pointer of Data</FolderTitle>
			<ArraySize>10</ArraySize>
			<NoResetByFramework>true</NoResetByFramework>
			<FolderVersion>$Rev$</FolderVersion>
			<FolderDescription>Folder to store calorimeter raw data.</FolderDescription>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData*</FieldType>
				<FieldComment>|| Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
		<Folder>
			<FolderName>RawPointerNoSplit</FolderName>
			<FolderTitle>Raw with pointer of Data</FolderTitle>
			<ArraySize>10</ArraySize>
			<NoResetByFramework>true</NoResetByFramework>
			<FolderVersion>$Rev$</FolderVersion>
			<FolderDescription>Folder to store calorimeter raw data.</FolderDescription>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData*</FieldType>
				<FieldComment>|| Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
		<Folder>
			<FolderName>RawSplit</FolderName>
			<FolderTitle>Raw with Data</FolderTitle>
			<ArraySize>10</ArraySize>
			<NoResetByFramework>true</NoResetByFramework>
			<FolderVersion>$Rev$</FolderVersion>
			<FolderDescription>Folder to store calorimeter raw data.</FolderDescription>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData</FieldType>
				<FieldComment>|| Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
		<Folder>
			<FolderName>RawNoSplit</FolderName>
			<FolderTitle>Raw with Data</FolderTitle>
			<ArraySize>10</ArraySize>
			<NoResetByFramework>true</NoResetByFramework>
			<FolderVersion>$Rev$</FolderVersion>
			<FolderDescription>Folder to store calorimeter raw data.</FolderDescription>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData</FieldType>
				<FieldComment>|| Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillTree</TaskName>
		</Task>
		<Task>
			<TaskName>PrintValue</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>MyTree</TreeName>
			<Branch>
				<BranchName>TrackBranch</BranchName>
				<RelatedFolder>Track</RelatedFolder>
			</Branch>
			<Branch>
				<BranchName>RawPointerSplitBranch</BranchName>
				<RelatedFolder>RawPointerSplit</RelatedFolder>
				<SplitLevel>99</SplitLevel>
			</Branch>
			<Branch>
				<BranchName>RawPointerNoSplitBranch</BranchName>
				<RelatedFolder>RawPointerNoSplit</RelatedFolder>
				<SplitLevel>0</SplitLevel>
			</Branch>
			<Branch>
				<BranchName>RawSplitBranch</BranchName>
				<RelatedFolder>RawSplit</RelatedFolder>
				<SplitLevel>99</SplitLevel>
			</Branch>
			<Branch>
				<BranchName>RawNoSplitBranch</BranchName>
				<RelatedFolder>RawNoSplit</RelatedFolder>
				<SplitLevel>0</SplitLevel>
			</Branch>
		</Tree>
	</Trees>
	<UserMakeFile>
		<DictionaryHeaders>
			<Header>
				<HeaderName>$(ROMESYS)/examples/tree_write_read2/RawData.h</HeaderName>
			</Header>
		</DictionaryHeaders>
		<AdditionalFiles>
			<File>
				<SourceFile>$(ROMESYS)/examples/tree_write_read2/RawData.cpp</SourceFile>
			</File>
		</AdditionalFiles>AdditionalFiles>
	</UserMakeFile>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/userMakefile/userMakefile.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>UMF</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Tasks>
		<Task>
			<TaskName>FillRawData</TaskName>
		</Task>
	</Tasks>
	<Folders>
		<Folder>
			<FolderName>Raw</FolderName>
			<FolderTitle>Raw Data</FolderTitle>
			<ArraySize>10</ArraySize>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData</FieldType>
				<FieldComment>Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
	</Folders>
	<Trees>
		<Tree>
			<TreeName>MyTree</TreeName>
			<Branch>
				<BranchName>Raw</BranchName>
				<RelatedFolder>Raw</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/basefolder/basefolder.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>BF</ExperimentShortCut>
		<ProgramName>Sample</ProgramName>
		<ProgramDefinitionVersion>$Rev$</ProgramDefinitionVersion>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>MyFolder</FolderName>
                        <DataBaseAccess>true</DataBaseAccess>
			<Inherit>MyBaseFolder</Inherit>
			<Field>
				<FieldName>MyValue</FieldName>
				<FieldType>Int_t</FieldType>
                                <DataBaseName>mydatabase</DataBaseName>
                                <DataBasePath>"/CCC[id=#]/BBB/bbb"</DataBasePath>
			</Field>
		</Folder>
		<Folder>
			<FolderName>MyBaseFolder</FolderName>
                        <DataBaseAccess>true</DataBaseAccess>
			<Inherit>MyBaseBaseFolder</Inherit>
			<Field>
				<FieldName>MyBaseValue</FieldName>
				<FieldType>Int_t</FieldType>
                                <DataBaseName>mydatabase</DataBaseName>
                                <DataBasePath>"/BBB[id=#]/BBB/bbb"</DataBasePath>
			</Field>
		</Folder>
		<Folder>
			<FolderName>MyBaseBaseFolder</FolderName>
                        <DataBaseAccess>true</DataBaseAccess>
			<Field>
				<FieldName>MyBaseBaseValue</FieldName>
				<FieldType>Int_t</FieldType>
                                <DataBaseName>mydatabase</DataBaseName>
                                <DataBasePath>"/AAA[id=#]/BBB/bbb"</DataBasePath>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillFolder</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>MyTree</TreeName>
			<Branch>
				<BranchName>MyBranch</BranchName>
				<RelatedFolder>MyFolder</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/examples/runheader/runheader.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>RUNH</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>RunInfo</FolderName>
			<Field>
				<FieldName>TriggerType</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Type of trigger of the run</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>Calibration</FolderName>
			<ArraySize>10</ArraySize>
			<Field>
				<FieldName>Pedestal</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Calibratin parameter of ADC</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>EventData</FolderName>
			<Field>
				<FieldName>ADC</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>ADC Value</FieldComment>
				<ArraySize>10</ArraySize>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>Task1</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<RunHeader>
				<RunHeaderName>runinfo</RunHeaderName>
				<RelatedFolder>RunInfo</RelatedFolder>
			</RunHeader>
			<RunHeader>
				<RunHeaderName>calib</RunHeaderName>
				<RelatedFolder>Calibration</RelatedFolder>
			</RunHeader>
			<Branch>
				<BranchName>data</BranchName>
				<RelatedFolder>EventData</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
	<GlobalSteeringParameters>
		<SteeringParameterField>
			<SPFieldName>TriggerType</SPFieldName>
			<SPFieldType>Int_t</SPFieldType>
		</SteeringParameterField>
	</GlobalSteeringParameters>
</ROMEFrameworkDefinition>
