=== cjpl/rome/rome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Described some enumerated types</xs:documentation>
	</xs:annotation>
	<xs:simpleType name="RootType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Float_t"/>
			<xs:enumeration value="ULong_t"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IncludeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="global"/>
			<xs:enumeration value="local"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HistTypeDesc">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TH1C"/>
			<xs:enumeration value="TH1D"/>
			<xs:enumeration value="TH1F"/>
			<xs:enumeration value="TH1I"/>
			<xs:enumeration value="TH1S"/>
			<xs:enumeration value="TH2C"/>
			<xs:enumeration value="TH2D"/>
			<xs:enumeration value="TH2F"/>
			<xs:enumeration value="TH2I"/>
			<xs:enumeration value="TH2S"/>
			<xs:enumeration value="TH3C"/>
			<xs:enumeration value="TH3D"/>
			<xs:enumeration value="TH3F"/>
			<xs:enumeration value="TH3I"/>
			<xs:enumeration value="TH3S"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MidasType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DWORD"/>
			<xs:enumeration value="float"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation>
		<xs:documentation>Describe general types</xs:documentation>
	</xs:annotation>
	<xs:complexType name="AuthorDesc">
		<xs:sequence>
			<xs:element name="AuthorName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorInstitute" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorCollaboration" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AuthorEmail" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ExperimentDesc">
		<xs:sequence>
			<xs:element name="ExperimentName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ExperimentShortCut" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ProgramName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FrameworkDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IncludeDesc">
		<xs:sequence>
			<xs:element name="IncludeName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="IncludeType" type="IncludeType" default="global" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterFieldDesc">
		<xs:sequence>
			<xs:element name="SPFieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SPFieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SPFieldInitialization" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SPFieldComment" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterGroupDesc">
		<xs:sequence>
			<xs:element name="SPGroupName" type="xs:string"/>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe types used by subfolders</xs:documentation>
	</xs:annotation>
	<xs:complexType name="FieldDesc">
		<xs:sequence>
			<xs:element name="FieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FieldComment" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FieldInitialization" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ArraySize" type="xs:string" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataBasePath" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FolderDesc">
		<xs:sequence>
			<xs:element name="FolderName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="FolderTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ArraySize" type="xs:string" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataBaseAccess" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ChangeableClassFile" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FolderVersion" type="xs:integer" default="1" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FolderDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Include" type="IncludeDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Field" type="FieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Folder" type="FolderDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe tasks</xs:documentation>
	</xs:annotation>
	<xs:complexType name="HistogramDesc">
		<xs:sequence>
			<xs:element name="HistName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="HistTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistFolderName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistFolderTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistType" type="HistTypeDesc" minOccurs="1" maxOccurs="1"/>
			<xs:element name="HistArraySize" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistXmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistYmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZNbins" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZmin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="HistZmax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParametersDesc">
		<xs:sequence>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TaskDesc">
		<xs:sequence>
			<xs:element name="TaskName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TaskEventId" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TaskVersion" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TaskDescription" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Include" type="IncludeDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Histogram" type="HistogramDesc" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SteeringParameters" type="SteeringParametersDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe trees</xs:documentation>
	</xs:annotation>
	<xs:complexType name="BranchDesc">
		<xs:sequence>
			<xs:element name="BranchName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="RelatedFolder" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TreeDesc">
		<xs:sequence>
			<xs:element name="TreeName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TreeTitle" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Branch" type="BranchDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe elements used by MidasBanks</xs:documentation>
	</xs:annotation>
	<xs:complexType name="EventHeaderDesc">
		<xs:sequence>
			<xs:element name="Folder" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="EventId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TriggerMask" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SerialNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TimeStamp" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BankDesc">
		<xs:sequence>
			<xs:element name="BankName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankType" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BankFieldDesc">
		<xs:sequence>
			<xs:element name="BankFieldName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankFieldType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankFieldSize" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StructuredBankDesc">
		<xs:sequence>
			<xs:element name="BankName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="BankField" type="BankFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>Describe overall document</xs:documentation>
	</xs:annotation>
	<xs:element name="ROMEFrameworkDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Experiment" type="ExperimentDesc" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Author" type="AuthorDesc" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Folders" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Folder" type="FolderDesc" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Tasks" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Task" type="TaskDesc" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Trees" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Tree" type="TreeDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="GlobalSteeringParameters" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MidasBanks" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="EventHeader" type="EventHeaderDesc" minOccurs="0" maxOccurs="1"/>
							<xs:element name="Bank" type="BankDesc" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="StructuredBank" type="StructuredBankDesc" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cjpl/rome/examples/multirun/multirun.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>MR</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Tasks>
		<Task>
			<TaskName>FillHisto</TaskName>
			<Histogram>
				<HistName>MyHisto</HistName>
				<HistFolderName>myhistos</HistFolderName>
				<HistType>TH1F</HistType>
				<HistXLabel>X</HistXLabel>
				<HistYLabel>Entries</HistYLabel>
				<HistXNbins>100</HistXNbins>
				<HistXmin>-100</HistXmin>
				<HistXmax>100</HistXmax>
			</Histogram>
		</Task>
	</Tasks>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/stepbystepmydaq/stepbystepmydaq.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>XYZ</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>PMTData</FolderName>
			<ArraySize>10</ArraySize>
			<Field>
				<FieldName>ADC</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>ADC Value of a PMT</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>PrintADCValues</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<Branch>
				<BranchName>PMTDataBranch</BranchName>
				<RelatedFolder>PMTData</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
	<GlobalSteeringParameters>
		<SteeringParameterField>
			<SPFieldName>OutputOnOff</SPFieldName>
			<SPFieldType>bool</SPFieldType>
		</SteeringParameterField>
	</GlobalSteeringParameters>
	<UserDAQSystems>
		<UserDAQSystem>
			<DAQSystemName>mydaq</DAQSystemName>
		</UserDAQSystem>
	</UserDAQSystems>
</ROMEFrameworkDefinition>

=== cjpl/rome/examples/reference/reference.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>REF</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
		<ProgramDefinitionVersion>$Rev$</ProgramDefinitionVersion>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Hit</FolderName>
			<ArraySize>variable</ArraySize>
			<IgnoreTObjectStreamer>false</IgnoreTObjectStreamer>
			<Field>
				<FieldName>X</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>X of hit</FieldComment>
			</Field>
			<Field>
				<FieldName>Y</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>Y of hit</FieldComment>
			</Field>
			<Field>
				<FieldName>Z</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>Z of hit</FieldComment>
			</Field>
			<Field>
				<FieldName>T</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>T of hit</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>Cluster</FolderName>
			<ArraySize>variable</ArraySize>
			<IgnoreTObjectStreamer>false</IgnoreTObjectStreamer>
			<Include>
				<IncludeName>TRef.h</IncludeName>
			</Include>
			<Include>
				<IncludeName>TRefArray.h</IncludeName>
			</Include>
			<Field>
				<FieldName>Hit</FieldName>
				<FieldType>TRefArray</FieldType>
				<FieldComment>Array of reference to hits</FieldComment>
			</Field>
			<Field>
				<FieldName>FirstHit</FieldName>
				<FieldType>TRef</FieldType>
				<FieldComment>Reference to the first hit in the cluster</FieldComment>
			</Field>
			<Field>
				<FieldName>HitID</FieldName>
				<FieldType>TArrayI</FieldType>
				<FieldComment>Index of hits in 'Hit' folder. This is only for check if TRefArray works correctly.</FieldComment>
			</Field>
			<Field>
				<FieldName>FirstHitID</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Index of a hit in 'Hit' folder. This is only for check if TRefArray works correctly.</FieldComment>
			</Field>
			<Field>
				<FieldName>X</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>X of cluster</FieldComment>
			</Field>
			<Field>
				<FieldName>Y</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>Y of cluster</FieldComment>
			</Field>
			<Field>
				<FieldName>Z</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>Z of cluster</FieldComment>
			</Field>
			<Field>
				<FieldName>T</FieldName>
				<FieldType>Double_t</FieldType>
				<FieldComment>T of cluster</FieldComment>
			</Field>
		</Folder>
		<Folder>
			<FolderName>MainCluster</FolderName>
			<Include>
				<IncludeName>TRef.h</IncludeName>
			</Include>
			<Field>
				<FieldName>LargestCluster</FieldName>
				<FieldType>TRef</FieldType>
				<FieldComment>Reference to the largest cluster</FieldComment>
			</Field>
			<Field>
				<FieldName>LargestClusterID</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>Index of a cluster in 'Cluster' folder. This is only for check if TRef works correctly.</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillHits</TaskName>
		</Task>
		<Task>
			<TaskName>Clustering</TaskName>
		</Task>
		<Task>
			<TaskName>CheckReference</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<Branch>
				<BranchName>hits</BranchName>
				<RelatedFolder>Hit</RelatedFolder>
			</Branch>
			<Branch>
				<BranchName>clusters</BranchName>
				<RelatedFolder>Cluster</RelatedFolder>
			</Branch>
			<Branch>
				<BranchName>maincluster</BranchName>
				<RelatedFolder>MainCluster</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/taskhierarchy/taskhierarchy.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>TH</ExperimentShortCut>
		<ProgramName>Example</ProgramName>
	</Experiment>
	<Tasks>
		<Task>
			<TaskName>MyTask</TaskName>
			<SteeringParameters>
				<SteeringParameterField>
					<SPFieldName>output</SPFieldName>
					<SPFieldType>ROMEString</SPFieldType>
					<SPFieldInitialization>"xxx"</SPFieldInitialization>
				</SteeringParameterField>
			</SteeringParameters>
		</Task>
	</Tasks>
	<TaskHierarchy>
		<Task>
			<TaskName>MyTask</TaskName>
		</Task>
		<Task>
			<TaskName>MyTask</TaskName>
		</Task>
	</TaskHierarchy>
</ROMEFrameworkDefinition>

=== cjpl/rome/examples/tree_write_read2/tree_write_read2.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>TWR2</ExperimentShortCut>
		<ProgramName>Sample</ProgramName>
		<ProgramDefinitionVersion>$Rev$</ProgramDefinitionVersion>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Track</FolderName>
			<Field>
				<FieldName>ntrack</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment># of tracks</FieldComment>
				<FieldInitialization>0</FieldInitialization>
			</Field>
			<Field>
				<FieldName>particleid</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>[ntrack] geant particle code</FieldComment>
				<ArraySize>variable</ArraySize>
			</Field>
		</Folder>
		<Folder>
			<FolderName>Raw</FolderName>
			<FolderTitle>Raw</FolderTitle>
			<ArraySize>10</ArraySize>
			<NoResetByFramework>true</NoResetByFramework>
			<FolderVersion>$Rev$</FolderVersion>
			<FolderDescription>Folder to store calorimeter raw data.</FolderDescription>
			<Include>
				<IncludeName>RawData.h</IncludeName>
				<IncludeType>local</IncludeType>
			</Include>
			<Field>
				<FieldName>Data</FieldName>
				<FieldType>RawData</FieldType>
				<FieldComment>|| Raw Data</FieldComment>
				<InheritTObject>true</InheritTObject>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>FillTree</TaskName>
		</Task>
		<Task>
			<TaskName>PrintValue</TaskName>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>MyTree</TreeName>
			<Branch>
				<BranchName>TrackBranch</BranchName>
				<RelatedFolder>Track</RelatedFolder>
			</Branch>
			<Branch>
				<BranchName>RawDataBranch</BranchName>
				<RelatedFolder>Raw</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
	<UserMakeFile>
		<DictionaryHeaders>
			<Header>
				<HeaderName>$(ROMESYS)/examples/tree_write_read2/RawData.h</HeaderName>
			</Header>
		</DictionaryHeaders>
	</UserMakeFile>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/document/document.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
  <Experiment>
    <ExperimentShortCut>DOC</ExperimentShortCut>
    <ProgramName>Analyzer</ProgramName>
    <FrameworkDescription>Description of DOCAnalyzer</FrameworkDescription>
  </Experiment>
  <Folders>
    <Folder>
      <FolderName>Data</FolderName>
      <FolderDescription>Description of a folder</FolderDescription>
      <FolderShortDescription>Short description of a folder</FolderShortDescription>
      <Field>
        <FieldName>data</FieldName>
        <FieldType>Int_t</FieldType>
        <FieldComment>Description of a field</FieldComment>
      </Field>
    </Folder>
  </Folders>
  <Tasks>
    <Task>
      <TaskName>A</TaskName>
      <TaskDescription>Description of the task A</TaskDescription>
      <TaskShortDescription>Short description of the task A</TaskShortDescription>
    </Task>
    <Task>
      <TaskName>B</TaskName>
      <TaskDescription>Description of the task B</TaskDescription>
      <TaskConnectedFrom>A</TaskConnectedFrom>
    </Task>
    <Task>
      <TaskName>C</TaskName>
      <TaskDescription>Description of the task C</TaskDescription>
      <TaskConnectedFrom>B</TaskConnectedFrom>
    </Task>
    <Task>
      <TaskName>D</TaskName>
      <TaskDescription>Description of the task D</TaskDescription>
      <TaskConnectedFrom>B</TaskConnectedFrom>
    </Task>
    <Task>
      <TaskName>E</TaskName>
      <TaskDescription>Description of the task E</TaskDescription>
      <TaskConnectedFrom>C</TaskConnectedFrom>
    </Task>
    <Task>
      <TaskName>F</TaskName>
      <TaskDescription>Description of the task F</TaskDescription>
    </Task>
    <Task>
      <TaskName>G</TaskName>
      <TaskDescription>Description of the task G</TaskDescription>
    </Task>
    <Task>
      <TaskName>H</TaskName>
      <TaskDescription>Description of the task G</TaskDescription>
    </Task>
    <Task>
      <TaskName>I</TaskName>
      <TaskDescription>Description of the task G</TaskDescription>
    </Task>
    <Task>
      <TaskName>J</TaskName>
      <TaskDescription>Description of the task G</TaskDescription>
    </Task>
  </Tasks>
  <TaskHierarchy>
    <Task>
      <TaskName>A</TaskName>
    </Task>
    <Task>
      <TaskName>B</TaskName>
    </Task>
    <Task>
      <TaskName>C</TaskName>
    </Task>
    <Task>
      <TaskName>D</TaskName>
    </Task>
    <Task>
      <TaskName>E</TaskName>
      <Task>
        <TaskName>F</TaskName>
        <TaskConnectedFrom>E</TaskConnectedFrom>
        <Task>
          <TaskName>H</TaskName>
          <TaskConnectedFrom>F_0</TaskConnectedFrom>
        </Task>
      </Task>
      <Task>
        <TaskName>G</TaskName>
        <TaskConnectedFrom>F_0</TaskConnectedFrom>
      </Task>
      <Task>
        <TaskName>F</TaskName>
        <TaskConnectedFrom>G_0</TaskConnectedFrom>
      </Task>
      <Task>
        <TaskName>G</TaskName>
        <TaskConnectedFrom>F_1</TaskConnectedFrom>
        <Task>
          <TaskName>H</TaskName>
          <TaskConnectedFrom>G_1</TaskConnectedFrom>
        </Task>
      </Task>
    </Task>
    <Task>
      <TaskName>I</TaskName>
      <TaskConnectedFrom>G_1</TaskConnectedFrom>
      <TaskConnectedFrom>D</TaskConnectedFrom>
    </Task>
    <Task>
      <TaskName>J</TaskName>
    </Task>
  </TaskHierarchy>
  <GlobalSteeringParameters>
    <SteeringParameterField>
      <SPFieldName>SteerParam</SPFieldName>
      <SPFieldType>bool</SPFieldType>
      <SPFieldComment>Description of a steering parameter</SPFieldComment>
    </SteeringParameterField>
  </GlobalSteeringParameters>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/stepbystephisto/stepbystephisto.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>XYZ</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>PMTData</FolderName>
			<Field>
				<FieldName>ADC</FieldName>
				<FieldType>Int_t</FieldType>
				<FieldComment>ADC Value of a PMT</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>PrintADCValues</TaskName>
			<Histogram>
				<HistName>ADC</HistName>
				<HistFolderName>adc</HistFolderName>
				<HistType>TH1F</HistType>
				<HistXLabel>ADC []</HistXLabel>
				<HistYLabel>Entries</HistYLabel>
				<HistXNbins>100</HistXNbins>
				<HistXmin>0</HistXmin>
				<HistXmax>100</HistXmax>
			</Histogram>
		</Task>
	</Tasks>
	<Trees>
		<Tree>
			<TreeName>DataTree</TreeName>
			<Branch>
				<BranchName>PMTDataBranch</BranchName>
				<RelatedFolder>PMTData</RelatedFolder>
			</Branch>
		</Tree>
	</Trees>
	<GlobalSteeringParameters>
		<SteeringParameterField>
			<SPFieldName>OutputOnOff</SPFieldName>
			<SPFieldType>bool</SPFieldType>
		</SteeringParameterField>
	</GlobalSteeringParameters>
</ROMEFrameworkDefinition>

=== cjpl/rome/rome/examples/midas/midas.xml
<ROMEFrameworkDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/rome/rome.xsd">
	<Experiment>
		<ExperimentShortCut>MID</ExperimentShortCut>
		<ProgramName>Analyzer</ProgramName>
	</Experiment>
	<Folders>
		<Folder>
			<FolderName>Data</FolderName>
			<Field>
				<FieldName>ADC</FieldName>
				<FieldType>Int_t</FieldType>
				<ArraySize>8</ArraySize>
				<FieldComment>ADC Values</FieldComment>
			</Field>
			<Field>
				<FieldName>TDC</FieldName>
				<FieldType>Int_t</FieldType>
				<ArraySize>8</ArraySize>
				<FieldComment>TDC Values</FieldComment>
			</Field>
		</Folder>
	</Folders>
	<Tasks>
		<Task>
			<TaskName>PrintValues</TaskName>
		</Task>
	</Tasks>
	<MidasBanks>
		<EventDefinition>
			<EventName>Trigger</EventName>
			<EventID>1</EventID>
			<EventTriggerMask>-1</EventTriggerMask>
			<EventSamplingRate>2</EventSamplingRate>
			<Banks>
				<Bank>
					<BankName>ADC0</BankName>
					<BankType>WORD</BankType>
				</Bank>
				<Bank>
					<BankName>TDC0</BankName>
					<BankType>WORD</BankType>
				</Bank>
			</Banks>
		</EventDefinition>
	</MidasBanks>
</ROMEFrameworkDefinition>
