=== cjpl/rome/argus/trunk/argusConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Schema for a ARGUS configuration file.</xs:documentation>
	</xs:annotation>
	<xs:simpleType name="DataBaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none"/>
			<xs:enumeration value="xml"/>
			<xs:enumeration value="sql"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="WindowDesc">
		<xs:annotation>
			<xs:documentation>Describes the main window property.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Scale" type="xs:float" default="1.0" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Basic size of main window.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StatusBar" type="xs:boolean" default="true" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Basic size of main window.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DataBaseDesc">
		<xs:annotation>
			<xs:documentation>Describes the data base, to which the framework should be connected.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Type" type="DataBaseType" default="none">
				<xs:annotation>
					<xs:documentation>The type of the data base.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Connection" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The connection string to initialize the database. For xml: &quot;path;databasename&quot;. For sql: &quot;mysql://username:password@servername:portnumber/databasename&quot;.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OnlineDesc">
		<xs:annotation>
			<xs:documentation>Description of the online specific configuration.  Generated monitor program can access to online database (ODB) of remote MIDAS server.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Host" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The name of the host of the online experiment.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Experiment" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The name of the online experiment.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SocketInterfaceDesc">
		<xs:annotation>
			<xs:documentation>Description of the socket interface. Generated monitor program can access to an external program to take the objects such as ROME folders and histograms over a root socket interface.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Host" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The name of the server for the socket interface.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="PortNumber" type="xs:integer" default="9090" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The number of the port for the socket interface.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterFieldDesc">
		<xs:annotation>
			<xs:documentation>Description of the steering parameter fields.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="SPName" type="xs:string">
				<xs:annotation>
					<xs:documentation>The name of the steering parameter field.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SPValue" type="xs:string">
				<xs:annotation>
					<xs:documentation>The value of the steering parameter field.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SteeringParameterGroupDesc">
		<xs:annotation>
			<xs:documentation>Description of the steering parameter groups.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="SPGroupName" type="xs:string">
				<xs:annotation>
					<xs:documentation>The name of the steering parameter group.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Describes a steering parameter field.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Describes a steering parameter group.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TabDesc">
		<xs:annotation>
			<xs:documentation>Description of the tab configuration.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="TabName" type="xs:string">
				<xs:annotation>
					<xs:documentation>The name of the tab.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Active" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>Inactive tasks are not executed by the framework.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Describes a steering parameter field of a task.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Describes a steering parameter group of a task.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<!-- 
			<xs:element name="Tab" type="TabDesc" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Describes a sub-tab.</xs:documentation>
				</xs:annotation>
			</xs:element>
			-->
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConfigurationDesc">
		<xs:annotation>
			<xs:documentation>Description of the configuration.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Window" type="WindowDesc" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the socket interface.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DataBase" type="DataBaseDesc" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the data base, to which the framework should be connected.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Online" type="OnlineDesc" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the online specific configuration.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SocketInterface" type="SocketInterfaceDesc" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the socket interface.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Tabs" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the tabs.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tab" type="TabDesc" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Describes the tab configuration.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GlobalSteeringParameters" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Describes the global steering parameters configuration.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SteeringParameterField" type="SteeringParameterFieldDesc" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Describes a steering parameter field.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="SteeringParameterGroup" type="SteeringParameterGroupDesc" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Describes a steering parameter group.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Configuration">
		<xs:annotation>
			<xs:documentation>Configuration of a ROME Framework.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MainConfiguration" type="ConfigurationDesc">
					<xs:annotation>
						<xs:documentation>Describes the main framework configuration.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<!-- <xs:element name="RunConfiguration" type="ConfigurationDesc" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Describes a run configuration, which overrides the main configuration for the specified runs.</xs:documentation>
					</xs:annotation>
				</xs:element>
				-->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cjpl/rome/argus/tags/v1-03/examples/statusBar/argusConfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- created by MXML on Tue Apr 12 19:26:38 2005 -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/Argus/ArgusConfig.xsd">
  <MainConfiguration>
    <Window>
      <Scale>1.0</Scale>
      <StatusBar>true</StatusBar>
    </Window>
    <DataBase>
      <Type>none</Type>
      <Connection></Connection>
    </DataBase>
    <Online>
      <Host></Host>
      <Experiment></Experiment>
    </Online>
    <SocketInterface>
      <Host></Host>
      <PortNumber>9090</PortNumber>
    </SocketInterface>
    <Tabs>
      <Tab>
        <TabName>Tab1</TabName>
        <Active>true</Active>
        <SteeringParameterField>
          <SPName>text</SPName>
          <SPValue>steering parameter</SPValue>
        </SteeringParameterField>
      </Tab>
      <Tab>
        <TabName>Tab2</TabName>
        <Active>true</Active>
      </Tab>
    </Tabs>
  </MainConfiguration>
</Configuration>

=== cjpl/rome/trunk/examples/histogram/argusConfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- created by ROME on Fri Mar 11 19:05:35 2005
 -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="c:/Argus/ArgusConfig.xsd">
     <MainConfiguration>
          <Window>
               <Scale>1.0</Scale>
          </Window>
          <DataBase>
               <Type>none</Type>
               <Connection></Connection>
          </DataBase>
          <Online>
               <Host></Host>
               <Experiment></Experiment>
          </Online>
          <SocketInterface>
               <Host>localhost</Host>
               <PortNumber>9090</PortNumber>
          </SocketInterface>
          <Tabs>
               <Tab>
                    <TabName>Tab</TabName>
                    <Active>true</Active>
               </Tab>
          </Tabs>
     </MainConfiguration>
</Configuration>
